# docker run -d --name prometheus  \
# -p 9090:9090 \
# -v /home/ubuntu/prometheus_config.yml:/etc/prometheus/prometheus.yml \
# prom/prometheus

global:
  # scrape_interval: 15s
  scrape_interval: 1s

scrape_configs:
  - job_name: 'profile-service-stg'
    static_configs:
      - targets: ['13.234.232.226:9100']
  - job_name: YourGuide
    honor_labels: false
    static_configs:
      - targets: ['localhost:9091']
        labels:
          pushgateway_instance: TimeStamp
